---
title: "Analisis_avanzado"
output: html_document
---

# Análisis Avanzado 

## Modificación del dataset
```{r}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("tidyverse","cluster", "factoextra","NbClust","tidyr","dplyr")
ipak(packages)
```


```{r}
# Leemos los datos del CSV
data <- read.csv('heart.csv')

# Creamos los datos de forma aleatoria
weigth <- sample(c(6000:15000), 918, replace = TRUE)/100
heigth <- sample(c(140:200), 918, replace = TRUE)/100
countries <- c('Spain', 'France', 'Germany', 'England', 'Portugal', 'Cuba', 'China', 'South Africa', 'Italy')
country <- sample(countries, 918, replace = TRUE)

# Los agregamos al dataframe
data$Weigth <- weigth
data$Heigth <- heigth
data$Country <- country

# Visualizamos los datos
View(data)

# Exportamos los nuevos datos a un CSV
write.csv(data,"heart3.csv", row.names = FALSE)
```

## Preprocesamiento y visualización de datos

```{r}
#all character columns to factor:
heart2df <- mutate_if(data, is.character, as.factor)
#all factor columns to integer:
heart2df <- mutate_if(heart2df, is.factor, as.integer)

```



## Aplicación del análisis no supervisado

```{r}
#Cargar y utilizar función IPAK

df <-heart2df

#normalizar las puntuaciones
df <- scale(df)
```

```{r}

#calcular la matriz de distacias
m.distancia <- get_dist(df, method = "euclidean") 

fviz_dist(m.distancia, gradient = list(low = "blue", mid = "white", high = "red"))
```


```{r}
#estimar el número de clústers
# wss, silhouette o gap_stat  method
fviz_nbclust(df, kmeans, method = "wss")
fviz_nbclust(df, kmeans, method = "silhouette")
fviz_nbclust(df, kmeans, method = "gap_stat")
```

```{r}

#calculamos los dos clústers
k2 <- kmeans(df, centers = 2, nstart = 25)
k2
str(k2)

#plotear los cluster
fviz_cluster(k2, data = df)
fviz_cluster(k2, data = df, ellipse.type = "euclid",repel = TRUE,star.plot = TRUE) #ellipse.type= "t", "norm", "euclid"
fviz_cluster(k2, data = df, ellipse.type = "norm")
fviz_cluster(k2, data = df, ellipse.type = "norm",palette = "Set2", ggtheme = theme_minimal())

res2 <- hcut(df, k = 2, stand = TRUE)
```


```{r}
df <-heart2df
df <- scale(df)
df<- as.data.frame(df)
df$clus<-as.factor(k2$cluster)
df

df$clus<-factor(df$clus)
data_long <- gather(df, caracteristica, valor, Age:Country, factor_key=TRUE)
data_long

ggplot(data_long, aes(as.factor(x = caracteristica), y = valor,group=clus, colour = clus)) +
  stat_summary(fun = mean, geom="pointrange", size = 1)+
  stat_summary(geom="line")

ggsave(file="procesamiento_NO_Jerárquico(kmeans).pdf", width=15, height=15, dpi=1000)
```